### ISSUE TITLE
Web API Core 2.1.0 Testing Tools

### ISSUE THREAD

**Issue by darnjo** [RESOStandards/web-api-commander#143]
The [Web API Core 2.1.0 testing rules were approved](https://github.com/RESOStandards/transport/issues/22). Testing tools may be created at this point.

**Tasks**
- [ ] Create Cucumber BDD tests from the approved testing rules
- [ ] Add support to read and produce reference files using the new flattened Data Dictionary reference sheet format
- [ ] Add backing code for the new tests
- [ ] Add versioned test targets to `build.gradle`
- [ ] Generate the appropriate report format
